const DUMMY_MOVIES = [
	{
		id: "f1",
		image:
			"https://m.media-amazon.com/images/M/MV5BMTM2MTI5NzA3MF5BMl5BanBnXkFtZTcwODExNTc0OA@@._V1_SX300.jpg",
		title: "Silver Linings Playbooks",
		year: "2012",
		type: "Movie",
		imdbRating: "7.7",
		genre: "Comedy, Drama, Romance",
		runtime: "122 min",
		language: "English",
		releaseDate: "25 Dec 2012",
		actors: "Bradley Cooper, Jennifer Lawrence, Robert De Niro",
		plot: "After a stint in a mental institution, former teacher Pat Solitano moves back in with his parents and tries to reconcile with his ex-wife. Things get more challenging when Pat meets Tiffany, a mysterious girl with problems of her own",
	},
	{
		id: "f2",
		image:
			"https://m.media-amazon.com/images/M/MV5BYWE3MDVkN2EtNjQ5MS00ZDQ4LTliNzYtMjc2YWMzMDEwMTA3XkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_SX300.jpg",
		title: "Squid Game",
		year: "2021",
		type: "Series",
		imdbRating: "8.2",
		genre: "Action, Drama, Mystery",
		runtime: "N/A",
		language: "Korean, English, Urdu",
		releaseDate: "17 Sep 2021",
		actors: "Lee Jung-jae, Park Hae-soo, Wi Ha-Joon",
		plot: "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits with deadly high stakes. A survival game that has a whopping 45.6 billion-won prize at stake.",
	},
	{
		id: "f3",
		image:
			"https://m.media-amazon.com/images/M/MV5BNDJjMzc4NGYtZmFmNS00YWY3LThjMzQtYzJlNGFkZGRiOWI1XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
		title: "Lucifer",
		year: "2016-2021",
		type: "Series",
		imdbRating: "8.1",
		genre: "Crime, Drama, Fantasy",
		runtime: "42 min",
		language: "English",
		releaseDate: "25 Jan 2016",
		actors: "Tom Ellis, Lauren German, Kevin Alejandro",
		plot: "Lucifer Morningstar has decided he's had enough of being the dutiful servant in Hell and decides to spend some time on Earth to better understand humanity. He settles in Los Angeles - the City of Angels.",
	},
	{
		id: "f4",
		image:
			"https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
		title: "Interstellar",
		year: "2014",
		type: "Movie",
		imdbRating: "8.6",
		genre: "Adventure, Drama, Sci-Fi",
		runtime: "169 min",
		language: "English",
		releaseDate: "07 Nov 2014",
		actors: "Matthew McConaughey, Anne Hathaway, Jessica Chastain",
		plot: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
	},
	{
		id: "f5",
		image:
			"https://m.media-amazon.com/images/M/MV5BMTM2MTI5NzA3MF5BMl5BanBnXkFtZTcwODExNTc0OA@@._V1_SX300.jpg",
		title: "Silver Linings Playbook",
		year: "2012",
		type: "Movie",
		imdbRating: "7.7",
		genre: "Comedy, Drama, Romance",
		runtime: "122 min",
		language: "English",
		releaseDate: "25 Dec 2012",
		actors: "Bradley Cooper, Jennifer Lawrence, Robert De Niro",
		plot: "After a stint in a mental institution, former teacher Pat Solitano moves back in with his parents and tries to reconcile with his ex-wife. Things get more challenging when Pat meets Tiffany, a mysterious girl with problems of her own",
	},
	{
		id: "f6",
		image:
			"https://m.media-amazon.com/images/M/MV5BYWE3MDVkN2EtNjQ5MS00ZDQ4LTliNzYtMjc2YWMzMDEwMTA3XkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_SX300.jpg",
		title: "Squid Game",
		year: "2021",
		type: "Series",
		imdbRating: "8.2",
		genre: "Action, Drama, Mystery",
		runtime: "N/A",
		language: "Korean, English, Urdu",
		releaseDate: "17 Sep 2021",
		actors: "Lee Jung-jae, Park Hae-soo, Wi Ha-Joon",
		plot: "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits with deadly high stakes. A survival game that has a whopping 45.6 billion-won prize at stake.",
	},
	{
		id: "f7",
		image:
			"https://m.media-amazon.com/images/M/MV5BNDJjMzc4NGYtZmFmNS00YWY3LThjMzQtYzJlNGFkZGRiOWI1XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
		title: "Lucifer",
		year: "2016-2021",
		type: "Series",
		imdbRating: "8.1",
		genre: "Crime, Drama, Fantasy",
		runtime: "42 min",
		language: "English",
		releaseDate: "25 Jan 2016",
		actors: "Tom Ellis, Lauren German, Kevin Alejandro",
		plot: "Lucifer Morningstar has decided he's had enough of being the dutiful servant in Hell and decides to spend some time on Earth to better understand humanity. He settles in Los Angeles - the City of Angels.",
	},
	{
		id: "f8",
		image:
			"https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
		title: "Interstellar",
		year: "2014",
		type: "Movie",
		imdbRating: "8.6",
		genre: "Adventure, Drama, Sci-Fi",
		runtime: "169 min",
		language: "English",
		releaseDate: "07 Nov 2014",
		actors: "Matthew McConaughey, Anne Hathaway, Jessica Chastain",
		plot: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
	},
];

export default DUMMY_MOVIES;
